language: python
python: '2.7'
script:
  - pwd
  - ls -al
  - cd ../
env:
  - APPDIR=iris_app_dir
before_deploy:
  - zip -r $TRAVIS_COMMIT $(git ls-files)
  - mkdir -p $DDIR
  - cp $TRAVIS_COMMIT.zip $APPDIR
deploy:
  - provider: s3
    skip-cleanup: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET
    region: $AWS_REGION
    local-dir: $APPDIR
    upload-dir: "build/$TRAVIS_BRANCH"
    on:
      branch: development
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    application: $AWS_APP_NAME
    deployment_group: $AWS_DEPLOYMENT_GROUP
    region: $AWS_REGION
    bucket: $AWS_BUCKET
    key: "build/$TRAVIS_BRANCH/$TRAVIS_COMMIT.zip"
    wait-until-deployed: true
    on:
      branch: development
after_deploy:
  - bootstrap/bootstrap.sh
  - pip install pip==9.0.3
  - pip install pipenv
  - pipenv install
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1920x1080x24+32 +extension GLX +extension RANDR > /dev/null 2>&1 &
  - sleep 3
  - pipenv run iris -j -n -d ci_tests
notifications:
  email:
    recipients:
      - rrobotin@mozilla.com
    on_success: always
    on_failure: always