language: python
python: '2.7'
script:
  - pwd
  - ls -al
env:
  - APPDIR=/rrobotin/iris
before_deploy:
  - pwd
  - git ls-files
  - zip -r $TRAVIS_COMMIT $(git ls-files)
  - sudo mkdir -p $APPDIR
  - sudo cp $TRAVIS_COMMIT.zip $APPDIR
deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    application: $AWS_APP_NAME
    deployment_group: $AWS_DEPLOYMENT_GROUP
    region: $AWS_REGION
    wait-until-deployed: true
    on:
      repo: rrobotin/iris
      branch: test_aws_ci
notifications:
  email:
    recipients:
      - rrobotin@mozilla.com
    on_success: always
    on_failure: always
